// Entire CLI extension for pi
// Auto-generated by `entire enable --agent pi`
// Do not edit manually — changes will be overwritten on next install.
//
// Forwards pi lifecycle events to `entire hooks pi <event>` so Entire can
// create checkpoints, capture transcripts, and offer rewind/resume.
//
// Events forwarded:
//   - session_start  → entire hooks pi session-start
//   - before_agent_start (first turn of a prompt) → entire hooks pi turn-start
//   - agent_end      → entire hooks pi turn-end
//   - session_compact → entire hooks pi compaction
//   - session_shutdown → entire hooks pi session-end
//
// All hooks receive a JSON payload on stdin:
//   { session_id, session_ref, prompt?, model? }
// where session_ref is the absolute path to the JSONL session file (or empty
// for in-memory/ephemeral sessions).

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

export default function (pi: ExtensionAPI) {
  // ENTIRE_CMD is replaced at install time by Entire's installer.
  const ENTIRE_CMD = "entire";

  // Track the current model so turn-start/turn-end can report it.
  let currentModel = "";

  function sessionRef(ctx: any): string {
    try {
      return ctx?.sessionManager?.getSessionFile?.() ?? "";
    } catch {
      return "";
    }
  }

  function sessionIdOf(ctx: any): string {
    try {
      return ctx?.sessionManager?.getSessionId?.() ?? "";
    } catch {
      return "";
    }
  }

  // Fire `entire hooks pi <hookName>` with a JSON payload on stdin.
  // Errors are swallowed — extension failures must never crash pi.
  async function callHook(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload) + "\n";
      // sh -c lets ENTIRE_CMD include shell substitutions (local-dev mode).
      const result = await pi.exec(
        "sh",
        ["-c", `${ENTIRE_CMD} hooks pi ${hookName}`],
        {
          input: json,
          timeout: 30_000,
        } as any,
      );
      void result;
    } catch {
      // Silently ignore — extension failures must not crash pi.
    }
  }

  pi.on("session_start", async (event: any, ctx: any) => {
    const session_id = sessionIdOf(ctx);
    if (!session_id) return;
    await callHook("session-start", {
      session_id,
      session_ref: sessionRef(ctx),
      reason: event?.reason ?? "",
    });
  });

  pi.on("before_agent_start", async (event: any, ctx: any) => {
    const session_id = sessionIdOf(ctx);
    if (!session_id) return;
    await callHook("turn-start", {
      session_id,
      session_ref: sessionRef(ctx),
      prompt: typeof event?.prompt === "string" ? event.prompt : "",
      model: currentModel,
    });
  });

  pi.on("model_select", async (event: any) => {
    const m = event?.model;
    if (m && typeof m.id === "string") {
      currentModel = m.provider ? `${m.provider}/${m.id}` : m.id;
    }
  });

  pi.on("agent_end", async (_event: any, ctx: any) => {
    const session_id = sessionIdOf(ctx);
    if (!session_id) return;
    await callHook("turn-end", {
      session_id,
      session_ref: sessionRef(ctx),
      model: currentModel,
    });
  });

  pi.on("session_compact", async (_event: any, ctx: any) => {
    const session_id = sessionIdOf(ctx);
    if (!session_id) return;
    await callHook("compaction", {
      session_id,
      session_ref: sessionRef(ctx),
    });
  });

  pi.on("session_shutdown", async (_event: any, ctx: any) => {
    const session_id = sessionIdOf(ctx);
    if (!session_id) return;
    await callHook("session-end", {
      session_id,
      session_ref: sessionRef(ctx),
    });
  });
}
