// Code generated by ogen, DO NOT EDIT.

package coreapi

import (
	"io"
	"mime"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/validate"
)

func decodeAddOrgMemberResponse(resp *http.Response) (res *MembershipStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *MembershipStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response Membership
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				return &MembershipStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeBatchLookupResponse(resp *http.Response) (res *BatchLookupOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *BatchLookupOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response BatchLookupOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &BatchLookupOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeCreateBindingResponse(resp *http.Response) (res *BindingStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *BindingStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response Binding
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				return &BindingStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeCreateMirrorResponse(resp *http.Response) (res *CreatedMirrorStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *CreatedMirrorStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response CreatedMirror
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				return &CreatedMirrorStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeCreateOrgResponse(resp *http.Response) (res *OrgStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *OrgStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response Org
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				return &OrgStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeCreateProjectResponse(resp *http.Response) (res *ProjectStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ProjectStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response Project
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &ProjectStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeCreateRepoResponse(resp *http.Response) (res *RepoStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *RepoStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response Repo
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &RepoStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeCreateServiceAccountResponse(resp *http.Response) (res *ServiceAccountStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ServiceAccountStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ServiceAccount
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				return &ServiceAccountStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeDeleteBindingResponse(resp *http.Response) (res *DeleteBinding2XX, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *DeleteBinding2XX, err error) {
			return &DeleteBinding2XX{
				StatusCode: resp.StatusCode,
			}, nil
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeDeleteMirrorResponse(resp *http.Response) (res *DeleteMirror2XX, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *DeleteMirror2XX, err error) {
			return &DeleteMirror2XX{
				StatusCode: resp.StatusCode,
			}, nil
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeDeleteRepoResponse(resp *http.Response) (res *DeleteRepo2XX, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *DeleteRepo2XX, err error) {
			return &DeleteRepo2XX{
				StatusCode: resp.StatusCode,
			}, nil
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeDeleteServiceAccountResponse(resp *http.Response) (res *DeleteServiceAccount2XX, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *DeleteServiceAccount2XX, err error) {
			return &DeleteServiceAccount2XX{
				StatusCode: resp.StatusCode,
			}, nil
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeGetMeResponse(resp *http.Response) (res *GetMeOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *GetMeOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response GetMeOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &GetMeOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeGetMirrorResponse(resp *http.Response) (res *MirrorStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *MirrorStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response Mirror
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				return &MirrorStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeGetPermissionsResponse(resp *http.Response) (res *GetPermissionsOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *GetPermissionsOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response GetPermissionsOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				return &GetPermissionsOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeGetRepoResponse(resp *http.Response) (res *RepoStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *RepoStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response Repo
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &RepoStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeGetServiceAccountResponse(resp *http.Response) (res *ServiceAccountStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ServiceAccountStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ServiceAccount
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				return &ServiceAccountStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeGrantProjectAccessResponse(resp *http.Response) (res *GrantProjectAccessOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *GrantProjectAccessOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response GrantProjectAccessOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				return &GrantProjectAccessOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeGrantRepoAccessResponse(resp *http.Response) (res *GrantRepoAccessOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *GrantRepoAccessOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response GrantRepoAccessOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				return &GrantRepoAccessOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeGrantServiceAccountAccessResponse(resp *http.Response) (res *GrantServiceAccountAccessOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *GrantServiceAccountAccessOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response GrantServiceAccountAccessOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				return &GrantServiceAccountAccessOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeListAuditEventsResponse(resp *http.Response) (res *ListAuditEventsOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ListAuditEventsOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ListAuditEventsOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &ListAuditEventsOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeListBindingsResponse(resp *http.Response) (res *ListBindingsOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ListBindingsOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ListBindingsOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &ListBindingsOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeListMirrorsResponse(resp *http.Response) (res *ListMirrorsOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ListMirrorsOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ListMirrorsOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &ListMirrorsOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeListOIDCProvidersResponse(resp *http.Response) (res *ListOIDCProvidersOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ListOIDCProvidersOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ListOIDCProvidersOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &ListOIDCProvidersOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeListOrgMembersResponse(resp *http.Response) (res *ListOrgMembersOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ListOrgMembersOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ListOrgMembersOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &ListOrgMembersOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeListOrgProjectsResponse(resp *http.Response) (res *ListOrgProjectsOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ListOrgProjectsOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ListOrgProjectsOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &ListOrgProjectsOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeListOrgsResponse(resp *http.Response) (res *ListOrgsOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ListOrgsOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ListOrgsOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &ListOrgsOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeListProjectMembersResponse(resp *http.Response) (res *ListProjectMembersOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ListProjectMembersOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ListProjectMembersOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &ListProjectMembersOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeListProjectReposResponse(resp *http.Response) (res *ListProjectReposOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ListProjectReposOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ListProjectReposOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &ListProjectReposOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeListProjectsResponse(resp *http.Response) (res *ListProjectsOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ListProjectsOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ListProjectsOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &ListProjectsOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeListServiceAccountGrantsResponse(resp *http.Response) (res *ListServiceAccountGrantsOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ListServiceAccountGrantsOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ListServiceAccountGrantsOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &ListServiceAccountGrantsOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeListServiceAccountsResponse(resp *http.Response) (res *ListServiceAccountsOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ListServiceAccountsOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ListServiceAccountsOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &ListServiceAccountsOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeLookupRepoByMirrorResponse(resp *http.Response) (res *MirrorRepoPathStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *MirrorRepoPathStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response MirrorRepoPath
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				return &MirrorRepoPathStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeLookupResourcesResponse(resp *http.Response) (res *LookupResourcesOutputBodyStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *LookupResourcesOutputBodyStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response LookupResourcesOutputBody
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				// Validate response.
				if err := func() error {
					if err := response.Validate(); err != nil {
						return err
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "validate")
				}
				return &LookupResourcesOutputBodyStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeRemoveOrgMemberResponse(resp *http.Response) (res *RemoveOrgMember2XX, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *RemoveOrgMember2XX, err error) {
			return &RemoveOrgMember2XX{
				StatusCode: resp.StatusCode,
			}, nil
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeResolveHandleResponse(resp *http.Response) (res *ResolvedIdentityStatusCode, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *ResolvedIdentityStatusCode, err error) {
			ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
			if err != nil {
				return res, errors.Wrap(err, "parse media type")
			}
			switch {
			case ct == "application/json":
				buf, err := io.ReadAll(resp.Body)
				if err != nil {
					return res, err
				}
				d := jx.DecodeBytes(buf)

				var response ResolvedIdentity
				if err := func() error {
					if err := response.Decode(d); err != nil {
						return err
					}
					if err := d.Skip(); err != io.EOF {
						return errors.New("unexpected trailing data")
					}
					return nil
				}(); err != nil {
					err = &ogenerrors.DecodeBodyError{
						ContentType: ct,
						Body:        buf,
						Err:         err,
					}
					return res, err
				}
				return &ResolvedIdentityStatusCode{
					StatusCode: resp.StatusCode,
					Response:   response,
				}, nil
			default:
				return res, validate.InvalidContentType(ct)
			}
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeRevokeProjectAccessResponse(resp *http.Response) (res *RevokeProjectAccess2XX, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *RevokeProjectAccess2XX, err error) {
			return &RevokeProjectAccess2XX{
				StatusCode: resp.StatusCode,
			}, nil
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeRevokeProjectAccessByProviderResponse(resp *http.Response) (res *RevokeProjectAccessByProvider2XX, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *RevokeProjectAccessByProvider2XX, err error) {
			return &RevokeProjectAccessByProvider2XX{
				StatusCode: resp.StatusCode,
			}, nil
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}

func decodeRevokeServiceAccountAccessResponse(resp *http.Response) (res *RevokeServiceAccountAccess2XX, _ error) {
	switch resp.StatusCode / 100 {
	case 2:
		// Pattern 2XX.
		res, err := func() (res *RevokeServiceAccountAccess2XX, err error) {
			return &RevokeServiceAccountAccess2XX{
				StatusCode: resp.StatusCode,
			}, nil
		}()
		if err != nil {
			return res, errors.Wrapf(err, "pattern 2XX (code %d)", resp.StatusCode)
		}
		return res, nil
	}
	// Convenient error response.
	defRes, err := func() (res *ErrorModelStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/problem+json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response ErrorModel
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &ErrorModelStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, errors.Wrap(defRes, "error")
}
